GET http://localhost:8000/order/3
Content-Type: application/json

# POST http://localhost:8000/order
# Content-Type: application/json

# {
#   "userId": "1",
#   "cartId": "3",
#   "shippingAddress": "asdasd",
#   "shippingPhone": "123124"
# }


